In [1]:
import numpy as np

In [2]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [3]:
len?

In [5]:
L = [1,2,3]
print(len(L) )

3


In [6]:
np?

In [8]:
# data typy in numpy
L = list(range(10))
L1 = [str(c) for c in L]
L2 = [True, "2", 3, 5]## element in list can have different data types
print(L, L1, L2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] [True, '2', 3, 5]


In [10]:
# fixed data-type in array of numpy
import array
A = array.array('i', L)
print ('numpy array A is: ', A)
print ('List L is: ', L)

# integer array
print ('Integer Array: ', np.array([1, 3, 5, 6]))

# float array
print ('Float Array:  ', np.array([1.1, 3, 5, 6]))
print ('Float Array:  ', np.array(L, dtype = 'float32'))

numpy array A is:  array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
List L is:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Integer Array:  [1 3 5 6]
Float Array:   [1.1 3.  5.  6. ]
Float Array:   [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [11]:
# nested lists result in multidimensional arrays
a1 = np.array([range(i, i+3) for i in [4, 7, 9]])
print ('Array a1 is: \n', a1)
print (a1.shape)
print ('the first row ', a1[0])
print ('the first column ', a1[:,0])
print ('the last row ', a1[-1])
print ('the last column ', a1[:, -1])

Array a1 is: 
 [[ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]
(3, 3)
the first row  [4 5 6]
the first column  [4 7 9]
the last row  [ 9 10 11]
the last column  [ 6  9 11]


In [12]:
# creating numpy array from scratch

# create 1-dimension array with 10 zeros
myzeros = np.zeros(10, dtype = int)
print (myzeros, '\n')

np.zeros(10, dtype = int)

[0 0 0 0 0 0 0 0 0 0] 



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# create 2-dimension array with 3x5  float ones
myones = np.ones((3, 5), dtype = float)
print (myones, '\n')

np.ones((3, 5), dtype = float)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# create a 3x5 array filled with 3.14
mypi = np.full((3, 5), 3.14)
print (mypi, '\n')

np.full((3, 5), 3.14)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]] 



array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# create an array filled with a linear sequence in range [0, 20), step-size = 2
# this is similar to range()
myRangeArr = np.arange(0, 20, 2)
print ('np.arange(0, 20, 2) is \n', myRangeArr)
print ('shape is \t', myRangeArr.shape, '\n')

np.arange(0, 20, 2)

np.arange(0, 20, 2) is 
 [ 0  2  4  6  8 10 12 14 16 18]
shape is 	 (10,) 



array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
print ('range(0, 20, 2) is \n', range(0, 20, 2))
print ('length of list is \t', len(range(0, 20, 2)), '\n')

range(0, 20, 2)

range(0, 20, 2) is 
 range(0, 20, 2)
length of list is 	 10 



range(0, 20, 2)

In [17]:
# create an array of 5 values evenly spaced between 0 and 1
print ('np.linspace(0, 1, 5) is \n', np.linspace(0, 1, 5))
print ('\n')

np.linspace(0, 1, 10)

np.linspace(0, 1, 5) is 
 [0.   0.25 0.5  0.75 1.  ]




array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
# create a 3x3 array of uniform distributed random values between 0 and 1
np.random.random((3,3))

array([[0.3306203 , 0.11383595, 0.27148394],
       [0.36078527, 0.02983777, 0.57729848],
       [0.49078413, 0.12063836, 0.50062419]])

In [19]:
# create a 3x4 array of normal distributed random values with mean = 0, standard deviation = 1
np.random.normal(0, 1, (3,4))

array([[ 1.55683291, -0.68741446,  0.6315123 ,  0.64297329],
       [ 0.51802468,  0.46777536,  2.00461784,  0.31238579],
       [-0.57513514,  0.33270312,  0.69895495,  1.14283339]])

In [20]:
# create a 3x4 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,4))

array([[7, 9, 5, 6],
       [2, 5, 4, 1],
       [0, 0, 0, 4]])

In [21]:
## create a 3x3 identity matrix
n = 3
np.eye(n)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
## create an uninitialized array with 3 integers
## the values will be whatever happens to already exist at that memory locaiton
print ('np.empty(3) is \n', np.empty(3), '\n')
print ('np.empty(3, dtype = int) is \n' , np.empty(3, dtype = int), '\n')
print ('np.empty(3, dtype = \'float32\') is \n', np.empty(3, dtype = 'float32'), '\n')

np.empty((3,4))

np.empty(3) is 
 [1. 1. 1.] 

np.empty(3, dtype = int) is 
 [16843009 16843009 16843009] 

np.empty(3, dtype = 'float32') is 
 [2.3694278e-38 2.3694278e-38 2.3694278e-38] 



array([[1.55683291, 0.68741446, 0.6315123 , 0.64297329],
       [0.51802468, 0.46777536, 2.00461784, 0.31238579],
       [0.57513514, 0.33270312, 0.69895495, 1.14283339]])

In [23]:
np.zeros(5, dtype = 'int8')

array([0, 0, 0, 0, 0], dtype=int8)

In [24]:
np.zeros(5, dtype = 'int16')

array([0, 0, 0, 0, 0], dtype=int16)

In [25]:
np.zeros(5, dtype = 'int32')

array([0, 0, 0, 0, 0])

In [26]:
np.zeros(5, dtype = 'int64')

array([0, 0, 0, 0, 0], dtype=int64)

In [27]:
np.zeros(5, dtype = np.int)

array([0, 0, 0, 0, 0])

In [28]:
np.zeros(5, dtype = float)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros(5, dtype = np.float)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones(5, dtype = 'float_')

array([1., 1., 1., 1., 1.])

In [31]:
np.ones(5, dtype = 'float64')

array([1., 1., 1., 1., 1.])

In [32]:
# create multiple random values with the same seed
np.random.seed(0)

x1 = np.random.randint(10, size = 6)      # create random integer in range [0, 10)
x2 = np.random.randint(10, 20, size = (3, 5))  # create random integer in range [10, 20)
x3 = np.random.randint(10, 20, size = (2, 3, 5))

print ('x1 is \n', x1, '\n')
print ('x2 is \n', x2, '\n')
print ('x3 is \n', x3, '\n')
print ('x1 dimension is \t', x1.ndim)
print ('x3 dimension is \t', x3.ndim)
print ('x3 shape is \t', x3.shape)
print ('x3 size is \t', x3.size)
print ('x3 data type is \t', x3.dtype)
print ('x3 item size is \t', x3.itemsize, 'bytes')
print ('x3 nbytes is \t', x3.nbytes, 'bytes')

x1 is 
 [5 0 3 3 7 9] 

x2 is 
 [[13 15 12 14 17]
 [16 18 18 11 16]
 [17 17 18 11 15]] 

x3 is 
 [[[19 18 19 14 13]
  [10 13 15 10 12]
  [13 18 11 13 13]]

 [[13 17 10 11 19]
  [19 10 14 17 13]
  [12 17 12 10 10]]] 

x1 dimension is 	 1
x3 dimension is 	 3
x3 shape is 	 (2, 3, 5)
x3 size is 	 30
x3 data type is 	 int32
x3 item size is 	 4 bytes
x3 nbytes is 	 120 bytes


In [33]:
# get help of this fucntion
? np.random.randint

In [34]:
# array indexing
print ('x3[0] is \n', x3[0], '\n')
print ('x3[0, 0] is \n', x3[0, 0], '\n')
print ('x3[0, 0, 0] is \n', x3[0, 0, 0], '\n')

x3[0] is 
 [[19 18 19 14 13]
 [10 13 15 10 12]
 [13 18 11 13 13]] 

x3[0, 0] is 
 [19 18 19 14 13] 

x3[0, 0, 0] is 
 19 



In [35]:
# array slicing: access  subarrays  x[start: stop: step]
x  = np.arange(11)    # return array with elements in range [0, 10), step-size = 1 (default)
? np.arange

print ('x is \t', x, '\n')
print ('x[:5] is \t', x[:5], '\n' )    #  x[:n] = subarray of x with index less than n
print ('x[2:5] is \t', x[2:5], '\n' )  #  x[m:n] = subarray of x with start-index = m, and end-index <n
print ('x[::2] is \t', x[::2], '\n' )  #  x[0: x.size: 2]

print ('x[1::2] is \t', x[1::2], '\n')   #  x[1: x.size: 2]

# reverse the array using negative index
print ('x[::-1] is \t', x[::-1], '\n' )     # reverse the array
print ('x[6::-1] is \t', x[6::-1], '\n' )      # reverse the subarray with index <=6 in x
print ('x[6::-2] is \t', x[6::-2], '\n' )      # reverse the subarray with index <=6 in x

x is 	 [ 0  1  2  3  4  5  6  7  8  9 10] 

x[:5] is 	 [0 1 2 3 4] 

x[2:5] is 	 [2 3 4] 

x[::2] is 	 [ 0  2  4  6  8 10] 

x[1::2] is 	 [1 3 5 7 9] 

x[::-1] is 	 [10  9  8  7  6  5  4  3  2  1  0] 

x[6::-1] is 	 [6 5 4 3 2 1 0] 

x[6::-2] is 	 [6 4 2 0] 



In [211]:
# slice of  multi-dimensional array
print 'x2 is \n', x2, '\n'
print 'x2 shape is \t', x2.shape, '\t dimension is \t', x2.ndim, '\t size is \t', x2.size, '\n'

print 'x2[:2, :3] is \n', x2[:2, :3], '\n'
print 'x2[:2, :] is \n', x2[:2, :], '\n'
print 'x2[:3, ::2] is \n', x2[:3, ::2], '\n'   # row index is 0,1, 2, and column index is 0,2,4
print 'x2[::-1, ::-2] is \n', x2[::-1,::-2], '\n'  # reverse sub-array
print 'x2[0] is \t', x2[0], '\n'
print 'x2[0, :] is \t', x2[0, :], '\n'

x2 is 
[[13 15 12 14 17]
 [16 18 18 11 16]
 [17 17 18 11 15]] 

x2 shape is 	(3L, 5L) 	 dimension is 	2 	 size is 	15 

x2[:2, :3] is 
[[13 15 12]
 [16 18 18]] 

x2[:2, :] is 
[[13 15 12 14 17]
 [16 18 18 11 16]] 

x2[:3, ::2] is 
[[13 12 17]
 [16 18 16]
 [17 18 15]] 

x2[::-1, ::-2] is 
[[15 18 17]
 [16 18 16]
 [17 12 13]] 

x2[0] is 	[13 15 12 14 17] 

x2[0, :] is 	[13 15 12 14 17] 



In [36]:
x2_sub = x2[:2, :3]
print ('x2_sub is \n', x2_sub, '\n')
print ('x2_sub[0] is \t', x2_sub[0], '\n')
print ('x2_sub[0][0] is \t', x2_sub[0][0], '\n')
print ('x2_sub[0, 0] is \t', x2_sub[0, 0], '\n')
x2

x2_sub is 
 [[13 15 12]
 [16 18 18]] 

x2_sub[0] is 	 [13 15 12] 

x2_sub[0][0] is 	 13 

x2_sub[0, 0] is 	 13 



array([[13, 15, 12, 14, 17],
       [16, 18, 18, 11, 16],
       [17, 17, 18, 11, 15]])

In [37]:
x2_sub[0, 0 ] = 99
print ('x2_sub is \n', x2_sub, '\n')
print ('x2 is \n', x2, '\n')

x2_sub is 
 [[99 15 12]
 [16 18 18]] 

x2 is 
 [[99 15 12 14 17]
 [16 18 18 11 16]
 [17 17 18 11 15]] 



In [41]:
# creating copies of array: copy() method
x2_sub_copy = x2[:2, :2].copy()
print('x2_sub_copy is \n', x2_sub_copy, '\n')

x2_sub_copy[0][0] = 129    # change the element in copy of array will not affect the original array
print('x2_sub_copy is \n', x2_sub_copy, '\n')
print('x2 is \n', x2, '\n')


x2_sub_copy is 
 [[99 15]
 [16 18]] 

x2_sub_copy is 
 [[129  15]
 [ 16  18]] 

x2 is 
 [[99 15 12 14 17]
 [16 18 18 11 16]
 [17 17 18 11 15]] 



In [49]:
# reshaping of arrays: reshape()  method
# Note: the size of the initial array must match the size of the reshaped array. 
np.arange(1, 10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
x = np.array([1,2, 3])
y = x.reshape((1,3))
y1 = x[np.newaxis, :]

print('y = x.reshape((1,3)) is \n', y, '\n')
print('y[0] is \t', y[0])
print('x is \t', x, '\n')
print('x[0] is \t', x[0])

print('\n')
print('y1 = x[np.newaxis, :] is \n', y1)
print('y1.shape is \t', y1.shape)

y = x.reshape((1,3)) is 
 [[1 2 3]] 

y[0] is 	 [1 2 3]
x is 	 [1 2 3] 

x[0] is 	 1


y1 = x[np.newaxis, :] is 
 [[1 2 3]]
y1.shape is 	 (1, 3)


In [71]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [82]:
np.array([1, 2, 3, 5]).reshape((2,2))[np.newaxis, :]

array([[[1, 2],
        [3, 5]]])

In [85]:
np.array([1, 2, 3, 5]).reshape((2,2))[np.newaxis, :, :]

array([[[1, 2],
        [3, 5]]])

In [87]:
np.array([1, 2, 3, 5]).reshape((2,2))[:, np.newaxis, :].shape

(2, 1, 2)

In [89]:
np.array([1, 2, 3, 5]).reshape((2,2))[:, :, np.newaxis].shape

(2, 2, 1)

In [ ]:
# concanate array
